#!/bin/sh
_DIR=$(cd "$(dirname "$0")"; pwd)
PYTHON=`which python3`

if [ "${_DIR}" == /opt/git-* ] && [[ -d /var/opt/hostpixel/bin/pyhon ]]; then
  PYTHON=/var/opt/hostpixel/bin/pyhon
fi

echo Python used: ${PYTHON}
cd "${_DIR}"
exec "${PYTHON}" -m cli $@
